const ResponseMessages = {
  PERMISSION_DENIED: "User has no permission",
  ACCOUNT_CREATED: "Account created",
  EMAIL_OR_MOBILE_EXITS: "User with the email or mobile already exists",
  EMAIL_ALREADY_EXIST: "User with the email already exists",
  USER_NOT_FOUND: "User with the email address not found",
  PASSWORD_DONT_MATCH: "Credentials of the user does'nt match",
  TOKEN_NOT_PRESENT: "Access denied. No token provided.",
  INVALID_TOKEN: "Invalid token",
  EMAIL_NOT_VERIFIED: "Email not verified",
  PROFILE_PIC_NOT_UPDATED: "Profile Picture not updated. Please try again",
  PROFILE_PIC_UPDATED: "Profile picture is updated successfully",
  USER_NOT_FOUND_WITH_TOKEN: "User not found",
  DATA_FAILDED_TO_INSERT: "Fail to insert data",
  UPDATE_FAILED: "Update data Failed",
  UPDATE_SUCCESSFULLY: "Update data Successfully",
  NO_DATA_FOUND: "No data found",
  DELETION_FAILED: "Deletion Failed",
  DELETION_SUCCESSFULLY: "Deleted successfully",
  NO_SCHEDULE: "No Schedule Found",
  SCHEDULE_SUCCESSFULLY: "Schedule Time Successfully",
  SCHEDULE_EXPIRED: "Schedule Time Expired",
  SCHEDULE_REJECTED: "Schedule Time Successfully Rejected",
  SCHEDULE_CANCELED: "Schedule Successfully Canceled",
  FAILED_TO_INSERT: "Unable to insert",
  NO_RATING_FOUND: "No Review or Rating Found",
  FAILED_TO_EDIT: "Failed to edit",
  NO_TIME_SLOT: "NO Time Slot",
  NO_SCHEDULE: "No Schedule Found",
  NO_SCHEDULE_FOUND: "No schedule found",
  SCHEDULE_ALREADY: "This time slot is already scheduled",
  FAILED_OPERATION: "Operation failed",
};

module.exports = ResponseMessages;
