const ResponseMessages = {
  EMAIL_OR_MOBILE_EXITS: "User with the email or mobile already exists",
  EMAIL_ALREADY_EXIST: "User with the email already exists",
  USER_NOT_FOUND: "User with the email address not found",
  PASSWORD_DONT_MATCH: "Credentials of the user does'nt match",
  TOKEN_NOT_PRESENT: "Access denied. No token provided.",
  INVALID_TOKEN: "Invalid token",
  EMAIL_NOT_VERIFIED: "Email not verified",
  PROFILE_PIC_NOT_UPDATED: "Profile Picture not updated. Please try again",
  PROFILE_PIC_UPDATED: "Profile picture is updated successfully",
  USER_NOT_FOUND_WITH_TOKEN: "User not found",
  DATA_FAILDED_TO_INSERT:"Fail to insert data",
  SENDING_EMAIL_FAILDED: "Sending Mail Failed",
  TEMPLATE_NOT_FOUND: "No template found",
  NO_CITY_FOUND:"No City Found",
  LINK_NOT_FOUND: "Link is not valid",
  ERROR_READING_HTML_FILE:"Error reading html file",
  UPDATE_FAILED:"Update data Failed",
  UPDATE_SUCCESSFULLY: "Update data Successfully",
  RECENT_CONSULTATION_NOT_FOUND : "Recent consultation Not found",
  CONSULTATION_SLOT_NOT_AVAILABLE : "Consultation slot is not available",
  NO_DATA_FOUND:"No data found",
  DELETION_FAILED:"Deletion Failed",
  DELETION_SUCCESSFULLY: "Deleted successfully",
  NO_SCHEDULE:"NO Schedule Found",
  SCHEDULE_SUCCESSFULLY:"Schedule Time Successfully",
  SCHEDULE_EXPIRED :"Schedule Time Expired",
  SCHEDULE_REJECTED :"Schedule Time Successfully Rejected",
  SCHEDULE_CANCELED: "Schedule Successfully Canceled",
  FAILED_TO_CONSULTATION:"Unable to create consultation, please try later!",
  NO_DOCTOR_OR_PATIENT: "No doctor or patient found",
  NO_DOCTOR: "No doctor found",
  NO_CONSULTATION_FOUND: "NO Consultation Found",
  FAILED_TO_INSERT:"Unable to insert",
  SMS_SEND_FAILED:"Sms sending failed",
  SMSBODY:"hai",
  NO_HOSPITAL_FOUND:"No Hospital Found",
  RESET_PASSWORD_MESSAGE:"Link To Rest Password",
  PASSWORD_UPDATE:"Password Update Successfully",
  FAILED_TO_CREATE_CARD:"Failed To Create Card",
  NO_CARD_FOUND:"NO Card Found",
  NO_USER_FOUND:"No User Found",
  NO_RATING_FOUND: "No Review or Rating Found",
  NO_TERMS_CONDITIONS_FOUND: "No Terms and Conditions Found",
  PASSWORD_ALREADY_UPDATE:"Password Already Updated",
  FAILED_TO_EDIT: "Failed to edit",
  SEND_FILE_SUCCESSFULLY: "Send File Successfully",
  SEND_RECOVERY_MAIL_SUCCESSFULLY : "Forget password link sended successfully",
  NO_TIME_SLOT:"NO Time Slot",
  NO_SCHEDULE: "No Schedule Found",
  SCHEDULE_MAIL_SEND: "Schedule Cancelled & Mail Send",
  NO_SCHEDULE_FOUND:"No schedule found",
  NO_TRANSACTIONID_FOUND:"Transaction Id not found",
  HEALTHCARD_NOT_FOUND:"Health card for this patient not found",
  FAILED_TO_CREATE_CARD:"Failed to create Health Card",
  SCHEDULE_MAIL_SEND: "Schedule Cancelled & Mail Send",
  NO_PAYMENT_REPORT_FOUND:"No payment report found",
  HEALTH_CARD_FOUND:"Health or Emirate card already added",
  SCHEDULE_ALREADY:"This time slot is already scheduled",
  NO_PATIENT_WAITING_ROOM:"No Patient Found",
  REFUND_SUCCESS:"Successfully refunded",
  REFUND_FAILED:"Refund Failed"
};

module.exports = ResponseMessages;
