const PermissionsList = {
  VIEW_ALL_SELLERS: "VIEW_ALL_SELLERS",
  VIEW_ALL_BUYERS: "VIEW_ALL_BUYERS",
  VIEW_MY_PROFILE: "VIEW_MY_PROFILE",
  UPDATE_MY_SLOTS: "UPDATE_MY_SLOTS",
  CREATE_APPOINTMENTS: "CREATE_APPOINTMENTS",
  VIEW_AVAILABLE_INTERVALS: "VIEW_AVAILABLE_INTERVALS",
  UPDATE_MY_PROFILE_PICTURE: "UPDATE_MY_PROFILE_PICTURE",
  EDIT_MY_PROFILE: "EDIT_MY_PROFILE",
  VIEW_MY_APPOINTMENTS: "VIEW_MY_APPOINTMENTS",
};
module.exports = PermissionsList;
